DROP INDEX IF EXISTS idx_appointment_client_id CASCADE;
DROP INDEX IF EXISTS idx_sharing_entity CASCADE;
DROP INDEX IF EXISTS idx_sharing_shared_to CASCADE;
DROP INDEX IF EXISTS idx_shared_documents_sharing CASCADE;
DROP INDEX IF EXISTS idx_shared_documents_category CASCADE;
DROP INDEX IF EXISTS idx_shared_documents_status CASCADE;
DROP INDEX IF EXISTS idx_share_requests_document CASCADE;
DROP INDEX IF EXISTS idx_share_requests_status CASCADE;
DROP INDEX IF EXISTS idx_share_requests_requester CASCADE;
DROP INDEX IF EXISTS idx_entity_review_entity CASCADE;
DROP INDEX IF EXISTS idx_entity_review_reviewer CASCADE;
DROP INDEX IF EXISTS idx_review_terms_entity_type CASCADE;
DROP INDEX IF EXISTS idx_reviews_table_entity_review CASCADE;
DROP INDEX IF EXISTS idx_reviews_table_review_term CASCADE;
DROP INDEX IF EXISTS idx_phases_projects_id CASCADE;
DROP INDEX IF EXISTS idx_property_entity CASCADE;
DROP INDEX IF EXISTS idx_property_property_type_id CASCADE;
DROP INDEX IF EXISTS idx_property_versions_property_id CASCADE;
DROP INDEX IF EXISTS hierarchical_location_view_location_id_idx CASCADE;
DROP INDEX IF EXISTS hierarchical_location_view_country_idx CASCADE;
DROP INDEX IF EXISTS hierarchical_location_view_state_idx CASCADE;
DROP INDEX IF EXISTS hierarchical_location_view_city_idx CASCADE;
DROP INDEX IF EXISTS hierarchical_location_view_community_idx CASCADE;
DROP INDEX IF EXISTS hierarchical_location_view_sub_community_idx CASCADE;
DROP INDEX IF EXISTS hierarchical_location_view_property_map_idx CASCADE;
DROP INDEX IF EXISTS hierarchical_location_view_location_string_idx CASCADE;
DROP INDEX IF EXISTS hierarchical_location_view_level_idx CASCADE;
DROP INDEX IF EXISTS hierarchical_location_view_search_idx CASCADE;

DROP INDEX IF EXISTS idx_project_search_ownership;
DROP INDEX IF EXISTS idx_project_search_completion_status;
DROP INDEX IF EXISTS idx_units_search_unittype;
DROP INDEX IF EXISTS idx_units_search_bathroom;
DROP INDEX IF EXISTS idx_units_search_bedroom;
DROP INDEX IF EXISTS idx_units_search_parking;
DROP INDEX IF EXISTS idx_property_search_propertytype;
DROP INDEX IF EXISTS idx_property_search;
DROP INDEX IF EXISTS idx_property_versions_search;
DROP INDEX IF EXISTS idx_units_search;
DROP INDEX IF EXISTS idx_unit_versions_search;
DROP INDEX IF EXISTS idx_media_entity_filter;
DROP INDEX IF EXISTS idx_media_media_type;
DROP INDEX IF EXISTS idx_media_entity_type_and_id;
DROP INDEX IF EXISTS idx_media_entity_id;
DROP INDEX IF EXISTS idx_media_entity_type;
DROP INDEX IF EXISTS idx_payment_plans_packages_entity;
DROP INDEX IF EXISTS idx_plan_installments_filter;
DROP INDEX IF EXISTS idx_swap_requirement_entity;
DROP INDEX IF EXISTS idx_swap_requirment_address_filter;
DROP INDEX IF EXISTS idx_facilities_amenities_join_check;
DROP INDEX IF EXISTS idx_facilities_amenities_type;
DROP INDEX IF EXISTS idx_facilities_amenities_entity_join_check;

DROP EXTENSION IF EXISTS pg_trgm CASCADE;