// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: industrial_properties_facts.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIndustrialPropertyFacts = `-- name: CreateIndustrialPropertyFacts :one
INSERT INTO industrial_properties_facts (
     bedroom,
     bathroom,
     plot_area,
     built_up_area,
     view,
     furnished,
     ownership,
     completion_status,
     start_date,
     completion_date,
     handover_date,
     no_of_floor,
     no_of_units,
     min_area,
     max_area,
     service_charge,
     parking,
     ask_price,
     price,
     rent_type,
     no_of_payment,
     no_of_retail,
     no_of_pool,
     elevator,
     starting_price,
     life_style,
     properties_id,
     property,
     is_branch,
     created_at,
     updated_at,
     available_units,
     commercial_tax,
     municipality_tax,
     workshop, 
     warehouse,
     office
)VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20,$21,$22,$23,$24,$25,$26,$27,$28, $29, $30, $31, $32, $33, $34, $35, $36, $37
) RETURNING id, bedroom, bathroom, plot_area, built_up_area, view, furnished, ownership, completion_status, start_date, completion_date, handover_date, no_of_floor, no_of_units, min_area, max_area, service_charge, parking, ask_price, price, rent_type, no_of_payment, no_of_retail, no_of_pool, elevator, starting_price, life_style, properties_id, property, is_branch, created_at, updated_at, available_units, commercial_tax, municipality_tax, workshop, warehouse, office
`

type CreateIndustrialPropertyFactsParams struct {
	Bedroom          pgtype.Text        `json:"bedroom"`
	Bathroom         pgtype.Int8        `json:"bathroom"`
	PlotArea         pgtype.Int8        `json:"plot_area"`
	BuiltUpArea      pgtype.Int8        `json:"built_up_area"`
	View             []int64            `json:"view"`
	Furnished        pgtype.Int8        `json:"furnished"`
	Ownership        pgtype.Int8        `json:"ownership"`
	CompletionStatus pgtype.Int8        `json:"completion_status"`
	StartDate        pgtype.Timestamptz `json:"start_date"`
	CompletionDate   pgtype.Timestamptz `json:"completion_date"`
	HandoverDate     pgtype.Timestamptz `json:"handover_date"`
	NoOfFloor        pgtype.Int8        `json:"no_of_floor"`
	NoOfUnits        pgtype.Int8        `json:"no_of_units"`
	MinArea          pgtype.Int8        `json:"min_area"`
	MaxArea          pgtype.Int8        `json:"max_area"`
	ServiceCharge    pgtype.Int8        `json:"service_charge"`
	Parking          pgtype.Int8        `json:"parking"`
	AskPrice         pgtype.Bool        `json:"ask_price"`
	Price            pgtype.Int8        `json:"price"`
	RentType         pgtype.Int8        `json:"rent_type"`
	NoOfPayment      pgtype.Int8        `json:"no_of_payment"`
	NoOfRetail       pgtype.Int8        `json:"no_of_retail"`
	NoOfPool         pgtype.Int8        `json:"no_of_pool"`
	Elevator         pgtype.Int8        `json:"elevator"`
	StartingPrice    pgtype.Int8        `json:"starting_price"`
	LifeStyle        pgtype.Int8        `json:"life_style"`
	PropertiesID     int64              `json:"properties_id"`
	Property         int64              `json:"property"`
	IsBranch         pgtype.Bool        `json:"is_branch"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
	AvailableUnits   pgtype.Int8        `json:"available_units"`
	CommercialTax    pgtype.Int8        `json:"commercial_tax"`
	MunicipalityTax  pgtype.Int8        `json:"municipality_tax"`
	Workshop         pgtype.Int8        `json:"workshop"`
	Warehouse        pgtype.Int8        `json:"warehouse"`
	Office           pgtype.Int8        `json:"office"`
}

func (q *Queries) CreateIndustrialPropertyFacts(ctx context.Context, arg CreateIndustrialPropertyFactsParams) (IndustrialPropertiesFact, error) {
	row := q.db.QueryRow(ctx, createIndustrialPropertyFacts,
		arg.Bedroom,
		arg.Bathroom,
		arg.PlotArea,
		arg.BuiltUpArea,
		arg.View,
		arg.Furnished,
		arg.Ownership,
		arg.CompletionStatus,
		arg.StartDate,
		arg.CompletionDate,
		arg.HandoverDate,
		arg.NoOfFloor,
		arg.NoOfUnits,
		arg.MinArea,
		arg.MaxArea,
		arg.ServiceCharge,
		arg.Parking,
		arg.AskPrice,
		arg.Price,
		arg.RentType,
		arg.NoOfPayment,
		arg.NoOfRetail,
		arg.NoOfPool,
		arg.Elevator,
		arg.StartingPrice,
		arg.LifeStyle,
		arg.PropertiesID,
		arg.Property,
		arg.IsBranch,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.AvailableUnits,
		arg.CommercialTax,
		arg.MunicipalityTax,
		arg.Workshop,
		arg.Warehouse,
		arg.Office,
	)
	var i IndustrialPropertiesFact
	err := row.Scan(
		&i.ID,
		&i.Bedroom,
		&i.Bathroom,
		&i.PlotArea,
		&i.BuiltUpArea,
		&i.View,
		&i.Furnished,
		&i.Ownership,
		&i.CompletionStatus,
		&i.StartDate,
		&i.CompletionDate,
		&i.HandoverDate,
		&i.NoOfFloor,
		&i.NoOfUnits,
		&i.MinArea,
		&i.MaxArea,
		&i.ServiceCharge,
		&i.Parking,
		&i.AskPrice,
		&i.Price,
		&i.RentType,
		&i.NoOfPayment,
		&i.NoOfRetail,
		&i.NoOfPool,
		&i.Elevator,
		&i.StartingPrice,
		&i.LifeStyle,
		&i.PropertiesID,
		&i.Property,
		&i.IsBranch,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AvailableUnits,
		&i.CommercialTax,
		&i.MunicipalityTax,
		&i.Workshop,
		&i.Warehouse,
		&i.Office,
	)
	return i, err
}

const deleteIndustrialPropertyFacts = `-- name: DeleteIndustrialPropertyFacts :exec
DELETE FROM industrial_properties_facts
Where id = $1
`

func (q *Queries) DeleteIndustrialPropertyFacts(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteIndustrialPropertyFacts, id)
	return err
}

const getAllIndustrialPropertyFacts = `-- name: GetAllIndustrialPropertyFacts :many
SELECT id, bedroom, bathroom, plot_area, built_up_area, view, furnished, ownership, completion_status, start_date, completion_date, handover_date, no_of_floor, no_of_units, min_area, max_area, service_charge, parking, ask_price, price, rent_type, no_of_payment, no_of_retail, no_of_pool, elevator, starting_price, life_style, properties_id, property, is_branch, created_at, updated_at, available_units, commercial_tax, municipality_tax, workshop, warehouse, office FROM industrial_properties_facts
ORDER BY id
LIMIT $1
OFFSET $2
`

type GetAllIndustrialPropertyFactsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetAllIndustrialPropertyFacts(ctx context.Context, arg GetAllIndustrialPropertyFactsParams) ([]IndustrialPropertiesFact, error) {
	rows, err := q.db.Query(ctx, getAllIndustrialPropertyFacts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IndustrialPropertiesFact
	for rows.Next() {
		var i IndustrialPropertiesFact
		if err := rows.Scan(
			&i.ID,
			&i.Bedroom,
			&i.Bathroom,
			&i.PlotArea,
			&i.BuiltUpArea,
			&i.View,
			&i.Furnished,
			&i.Ownership,
			&i.CompletionStatus,
			&i.StartDate,
			&i.CompletionDate,
			&i.HandoverDate,
			&i.NoOfFloor,
			&i.NoOfUnits,
			&i.MinArea,
			&i.MaxArea,
			&i.ServiceCharge,
			&i.Parking,
			&i.AskPrice,
			&i.Price,
			&i.RentType,
			&i.NoOfPayment,
			&i.NoOfRetail,
			&i.NoOfPool,
			&i.Elevator,
			&i.StartingPrice,
			&i.LifeStyle,
			&i.PropertiesID,
			&i.Property,
			&i.IsBranch,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AvailableUnits,
			&i.CommercialTax,
			&i.MunicipalityTax,
			&i.Workshop,
			&i.Warehouse,
			&i.Office,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIndustrialPropertyFacts = `-- name: GetIndustrialPropertyFacts :one
SELECT id, bedroom, bathroom, plot_area, built_up_area, view, furnished, ownership, completion_status, start_date, completion_date, handover_date, no_of_floor, no_of_units, min_area, max_area, service_charge, parking, ask_price, price, rent_type, no_of_payment, no_of_retail, no_of_pool, elevator, starting_price, life_style, properties_id, property, is_branch, created_at, updated_at, available_units, commercial_tax, municipality_tax, workshop, warehouse, office FROM industrial_properties_facts 
WHERE id = $1 LIMIT $1
`

func (q *Queries) GetIndustrialPropertyFacts(ctx context.Context, limit int32) (IndustrialPropertiesFact, error) {
	row := q.db.QueryRow(ctx, getIndustrialPropertyFacts, limit)
	var i IndustrialPropertiesFact
	err := row.Scan(
		&i.ID,
		&i.Bedroom,
		&i.Bathroom,
		&i.PlotArea,
		&i.BuiltUpArea,
		&i.View,
		&i.Furnished,
		&i.Ownership,
		&i.CompletionStatus,
		&i.StartDate,
		&i.CompletionDate,
		&i.HandoverDate,
		&i.NoOfFloor,
		&i.NoOfUnits,
		&i.MinArea,
		&i.MaxArea,
		&i.ServiceCharge,
		&i.Parking,
		&i.AskPrice,
		&i.Price,
		&i.RentType,
		&i.NoOfPayment,
		&i.NoOfRetail,
		&i.NoOfPool,
		&i.Elevator,
		&i.StartingPrice,
		&i.LifeStyle,
		&i.PropertiesID,
		&i.Property,
		&i.IsBranch,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AvailableUnits,
		&i.CommercialTax,
		&i.MunicipalityTax,
		&i.Workshop,
		&i.Warehouse,
		&i.Office,
	)
	return i, err
}

const getIndustrialPropertyFactsByIndustryProperties = `-- name: GetIndustrialPropertyFactsByIndustryProperties :one
SELECT id, bedroom, bathroom, plot_area, built_up_area, view, furnished, ownership, completion_status, start_date, completion_date, handover_date, no_of_floor, no_of_units, min_area, max_area, service_charge, parking, ask_price, price, rent_type, no_of_payment, no_of_retail, no_of_pool, elevator, starting_price, life_style, properties_id, property, is_branch, created_at, updated_at, available_units, commercial_tax, municipality_tax, workshop, warehouse, office FROM industrial_properties_facts 
WHERE industrial_properties_facts.properties_id = $1 AND industrial_properties_facts.property = $2 AND industrial_properties_facts.is_branch = $3
`

type GetIndustrialPropertyFactsByIndustryPropertiesParams struct {
	PropertiesID int64       `json:"properties_id"`
	Property     int64       `json:"property"`
	IsBranch     pgtype.Bool `json:"is_branch"`
}

func (q *Queries) GetIndustrialPropertyFactsByIndustryProperties(ctx context.Context, arg GetIndustrialPropertyFactsByIndustryPropertiesParams) (IndustrialPropertiesFact, error) {
	row := q.db.QueryRow(ctx, getIndustrialPropertyFactsByIndustryProperties, arg.PropertiesID, arg.Property, arg.IsBranch)
	var i IndustrialPropertiesFact
	err := row.Scan(
		&i.ID,
		&i.Bedroom,
		&i.Bathroom,
		&i.PlotArea,
		&i.BuiltUpArea,
		&i.View,
		&i.Furnished,
		&i.Ownership,
		&i.CompletionStatus,
		&i.StartDate,
		&i.CompletionDate,
		&i.HandoverDate,
		&i.NoOfFloor,
		&i.NoOfUnits,
		&i.MinArea,
		&i.MaxArea,
		&i.ServiceCharge,
		&i.Parking,
		&i.AskPrice,
		&i.Price,
		&i.RentType,
		&i.NoOfPayment,
		&i.NoOfRetail,
		&i.NoOfPool,
		&i.Elevator,
		&i.StartingPrice,
		&i.LifeStyle,
		&i.PropertiesID,
		&i.Property,
		&i.IsBranch,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AvailableUnits,
		&i.CommercialTax,
		&i.MunicipalityTax,
		&i.Workshop,
		&i.Warehouse,
		&i.Office,
	)
	return i, err
}

const getIndustrialPropertyFactsByProperties = `-- name: GetIndustrialPropertyFactsByProperties :one
SELECT id, bedroom, bathroom, plot_area, built_up_area, view, furnished, ownership, completion_status, start_date, completion_date, handover_date, no_of_floor, no_of_units, min_area, max_area, service_charge, parking, ask_price, price, rent_type, no_of_payment, no_of_retail, no_of_pool, elevator, starting_price, life_style, properties_id, property, is_branch, created_at, updated_at, available_units, commercial_tax, municipality_tax, workshop, warehouse, office FROM industrial_properties_facts
WHERE industrial_properties_facts.properties_id = $1 AND industrial_properties_facts.property = $2 AND industrial_properties_facts.is_branch = $3
`

type GetIndustrialPropertyFactsByPropertiesParams struct {
	PropertiesID int64       `json:"properties_id"`
	Property     int64       `json:"property"`
	IsBranch     pgtype.Bool `json:"is_branch"`
}

func (q *Queries) GetIndustrialPropertyFactsByProperties(ctx context.Context, arg GetIndustrialPropertyFactsByPropertiesParams) (IndustrialPropertiesFact, error) {
	row := q.db.QueryRow(ctx, getIndustrialPropertyFactsByProperties, arg.PropertiesID, arg.Property, arg.IsBranch)
	var i IndustrialPropertiesFact
	err := row.Scan(
		&i.ID,
		&i.Bedroom,
		&i.Bathroom,
		&i.PlotArea,
		&i.BuiltUpArea,
		&i.View,
		&i.Furnished,
		&i.Ownership,
		&i.CompletionStatus,
		&i.StartDate,
		&i.CompletionDate,
		&i.HandoverDate,
		&i.NoOfFloor,
		&i.NoOfUnits,
		&i.MinArea,
		&i.MaxArea,
		&i.ServiceCharge,
		&i.Parking,
		&i.AskPrice,
		&i.Price,
		&i.RentType,
		&i.NoOfPayment,
		&i.NoOfRetail,
		&i.NoOfPool,
		&i.Elevator,
		&i.StartingPrice,
		&i.LifeStyle,
		&i.PropertiesID,
		&i.Property,
		&i.IsBranch,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AvailableUnits,
		&i.CommercialTax,
		&i.MunicipalityTax,
		&i.Workshop,
		&i.Warehouse,
		&i.Office,
	)
	return i, err
}

const updateIndustrialPropertyFacts = `-- name: UpdateIndustrialPropertyFacts :one
UPDATE industrial_properties_facts
SET  bedroom = $2,
     bathroom = $3,
     plot_area = $4,
     built_up_area = $5,
     view = $6,
     furnished = $7,
     ownership = $8,
     completion_status = $9,
     start_date = $10,
     completion_date = $11,
     handover_date = $12,
     no_of_floor = $13,
     no_of_units = $14,
     min_area = $15,
     max_area = $16,
     service_charge = $17,
     parking = $18,
     ask_price = $19,
     price = $20,
     rent_type = $21,
     no_of_payment = $22,
     no_of_retail = $23,
     no_of_pool = $24,
     elevator = $25,
     starting_price = $26,
     life_style = $27,
     properties_id = $28,
     property = $29,
     is_branch = $30,
     created_at = $31,
     updated_at = $32,
     available_units = $33,
     commercial_tax = $34,
     municipality_tax = $35,
     workshop = $36, 
     warehouse =  $37,
     office = $38
Where id = $1
RETURNING id, bedroom, bathroom, plot_area, built_up_area, view, furnished, ownership, completion_status, start_date, completion_date, handover_date, no_of_floor, no_of_units, min_area, max_area, service_charge, parking, ask_price, price, rent_type, no_of_payment, no_of_retail, no_of_pool, elevator, starting_price, life_style, properties_id, property, is_branch, created_at, updated_at, available_units, commercial_tax, municipality_tax, workshop, warehouse, office
`

type UpdateIndustrialPropertyFactsParams struct {
	ID               int64              `json:"id"`
	Bedroom          pgtype.Text        `json:"bedroom"`
	Bathroom         pgtype.Int8        `json:"bathroom"`
	PlotArea         pgtype.Int8        `json:"plot_area"`
	BuiltUpArea      pgtype.Int8        `json:"built_up_area"`
	View             []int64            `json:"view"`
	Furnished        pgtype.Int8        `json:"furnished"`
	Ownership        pgtype.Int8        `json:"ownership"`
	CompletionStatus pgtype.Int8        `json:"completion_status"`
	StartDate        pgtype.Timestamptz `json:"start_date"`
	CompletionDate   pgtype.Timestamptz `json:"completion_date"`
	HandoverDate     pgtype.Timestamptz `json:"handover_date"`
	NoOfFloor        pgtype.Int8        `json:"no_of_floor"`
	NoOfUnits        pgtype.Int8        `json:"no_of_units"`
	MinArea          pgtype.Int8        `json:"min_area"`
	MaxArea          pgtype.Int8        `json:"max_area"`
	ServiceCharge    pgtype.Int8        `json:"service_charge"`
	Parking          pgtype.Int8        `json:"parking"`
	AskPrice         pgtype.Bool        `json:"ask_price"`
	Price            pgtype.Int8        `json:"price"`
	RentType         pgtype.Int8        `json:"rent_type"`
	NoOfPayment      pgtype.Int8        `json:"no_of_payment"`
	NoOfRetail       pgtype.Int8        `json:"no_of_retail"`
	NoOfPool         pgtype.Int8        `json:"no_of_pool"`
	Elevator         pgtype.Int8        `json:"elevator"`
	StartingPrice    pgtype.Int8        `json:"starting_price"`
	LifeStyle        pgtype.Int8        `json:"life_style"`
	PropertiesID     int64              `json:"properties_id"`
	Property         int64              `json:"property"`
	IsBranch         pgtype.Bool        `json:"is_branch"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
	AvailableUnits   pgtype.Int8        `json:"available_units"`
	CommercialTax    pgtype.Int8        `json:"commercial_tax"`
	MunicipalityTax  pgtype.Int8        `json:"municipality_tax"`
	Workshop         pgtype.Int8        `json:"workshop"`
	Warehouse        pgtype.Int8        `json:"warehouse"`
	Office           pgtype.Int8        `json:"office"`
}

func (q *Queries) UpdateIndustrialPropertyFacts(ctx context.Context, arg UpdateIndustrialPropertyFactsParams) (IndustrialPropertiesFact, error) {
	row := q.db.QueryRow(ctx, updateIndustrialPropertyFacts,
		arg.ID,
		arg.Bedroom,
		arg.Bathroom,
		arg.PlotArea,
		arg.BuiltUpArea,
		arg.View,
		arg.Furnished,
		arg.Ownership,
		arg.CompletionStatus,
		arg.StartDate,
		arg.CompletionDate,
		arg.HandoverDate,
		arg.NoOfFloor,
		arg.NoOfUnits,
		arg.MinArea,
		arg.MaxArea,
		arg.ServiceCharge,
		arg.Parking,
		arg.AskPrice,
		arg.Price,
		arg.RentType,
		arg.NoOfPayment,
		arg.NoOfRetail,
		arg.NoOfPool,
		arg.Elevator,
		arg.StartingPrice,
		arg.LifeStyle,
		arg.PropertiesID,
		arg.Property,
		arg.IsBranch,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.AvailableUnits,
		arg.CommercialTax,
		arg.MunicipalityTax,
		arg.Workshop,
		arg.Warehouse,
		arg.Office,
	)
	var i IndustrialPropertiesFact
	err := row.Scan(
		&i.ID,
		&i.Bedroom,
		&i.Bathroom,
		&i.PlotArea,
		&i.BuiltUpArea,
		&i.View,
		&i.Furnished,
		&i.Ownership,
		&i.CompletionStatus,
		&i.StartDate,
		&i.CompletionDate,
		&i.HandoverDate,
		&i.NoOfFloor,
		&i.NoOfUnits,
		&i.MinArea,
		&i.MaxArea,
		&i.ServiceCharge,
		&i.Parking,
		&i.AskPrice,
		&i.Price,
		&i.RentType,
		&i.NoOfPayment,
		&i.NoOfRetail,
		&i.NoOfPool,
		&i.Elevator,
		&i.StartingPrice,
		&i.LifeStyle,
		&i.PropertiesID,
		&i.Property,
		&i.IsBranch,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AvailableUnits,
		&i.CommercialTax,
		&i.MunicipalityTax,
		&i.Workshop,
		&i.Warehouse,
		&i.Office,
	)
	return i, err
}
