// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: mv.sql

package sqlc

import (
	"context"
)

const refreshAutoCompleteMV = `-- name: RefreshAutoCompleteMV :exec
SELECT refresh_autocomplete_view()
`

func (q *Queries) RefreshAutoCompleteMV(ctx context.Context) error {
	_, err := q.db.Exec(ctx, refreshAutoCompleteMV)
	return err
}

const refreshHierarchicalLocationMV = `-- name: RefreshHierarchicalLocationMV :exec
SELECT refresh_hierarchical_location_view()
`

func (q *Queries) RefreshHierarchicalLocationMV(ctx context.Context) error {
	_, err := q.db.Exec(ctx, refreshHierarchicalLocationMV)
	return err
}

const refreshPermissionsMV = `-- name: RefreshPermissionsMV :exec
SELECT refresh_permissions_mv()
`

func (q *Queries) RefreshPermissionsMV(ctx context.Context) error {
	_, err := q.db.Exec(ctx, refreshPermissionsMV)
	return err
}

const refreshQualityScoreMV = `-- name: RefreshQualityScoreMV :exec
SELECT refresh_property_quality_score()
`

func (q *Queries) RefreshQualityScoreMV(ctx context.Context) error {
	_, err := q.db.Exec(ctx, refreshQualityScoreMV)
	return err
}

const refreshSectionPermissionMV = `-- name: RefreshSectionPermissionMV :exec
SELECT refresh_section_permission_mv()
`

func (q *Queries) RefreshSectionPermissionMV(ctx context.Context) error {
	_, err := q.db.Exec(ctx, refreshSectionPermissionMV)
	return err
}

const refreshSubSectionMV = `-- name: RefreshSubSectionMV :exec
SELECT refresh_sub_section_mv()
`

func (q *Queries) RefreshSubSectionMV(ctx context.Context) error {
	_, err := q.db.Exec(ctx, refreshSubSectionMV)
	return err
}
