// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: owner_properties.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOwnerProperties = `-- name: CreateOwnerProperties :one
INSERT INTO owner_properties (
  list_of_date,
  list_of_notes,
  list_of_agent,
  property_title,
  property_title_arabic,
  description,
  description_arabic,
  is_verified,
  property_rank,
  addresses_id,
  locations_id,
  property_types_id,
  profiles_id,
  facilities_id,
  amenities_id,
  status,
  created_at,
  updated_at,
  is_show_owner_info,
  property,
  -- facts_values,
  countries_id,
  ref_no,
  category,
  investment,
  contract_start_datetime,
  contract_end_datetime,
  amount,
  -- ask_price,
  unit_types,
    users_id,
    property_name 
)VALUES (
    $1, $2, $3, $4, $5, $6,$7,$8,$9,$10, $11, $12, $13, $14,  $15, $16, $17, $18, $19, $20,$21, $22, $23, $24, $25, $26, $27,  $28, $29, $30 
) RETURNING id, property_title, property_title_arabic, description, description_arabic, is_verified, property_rank, addresses_id, locations_id, property_types_id, profiles_id, facilities_id, amenities_id, status, created_at, updated_at, is_show_owner_info, property, countries_id, ref_no, category, investment, contract_start_datetime, contract_end_datetime, amount, unit_types, users_id, property_name, list_of_date, list_of_notes, list_of_agent
`

type CreateOwnerPropertiesParams struct {
	ListOfDate            []time.Time        `json:"list_of_date"`
	ListOfNotes           []string           `json:"list_of_notes"`
	ListOfAgent           []int64            `json:"list_of_agent"`
	PropertyTitle         string             `json:"property_title"`
	PropertyTitleArabic   string             `json:"property_title_arabic"`
	Description           string             `json:"description"`
	DescriptionArabic     string             `json:"description_arabic"`
	IsVerified            pgtype.Bool        `json:"is_verified"`
	PropertyRank          int64              `json:"property_rank"`
	AddressesID           int64              `json:"addresses_id"`
	LocationsID           int64              `json:"locations_id"`
	PropertyTypesID       int64              `json:"property_types_id"`
	ProfilesID            int64              `json:"profiles_id"`
	FacilitiesID          []int64            `json:"facilities_id"`
	AmenitiesID           []int64            `json:"amenities_id"`
	Status                int64              `json:"status"`
	CreatedAt             time.Time          `json:"created_at"`
	UpdatedAt             time.Time          `json:"updated_at"`
	IsShowOwnerInfo       pgtype.Bool        `json:"is_show_owner_info"`
	Property              int64              `json:"property"`
	CountriesID           int64              `json:"countries_id"`
	RefNo                 string             `json:"ref_no"`
	Category              string             `json:"category"`
	Investment            pgtype.Bool        `json:"investment"`
	ContractStartDatetime pgtype.Timestamptz `json:"contract_start_datetime"`
	ContractEndDatetime   pgtype.Timestamptz `json:"contract_end_datetime"`
	Amount                float64            `json:"amount"`
	UnitTypes             []int64            `json:"unit_types"`
	UsersID               int64              `json:"users_id"`
	PropertyName          string             `json:"property_name"`
}

func (q *Queries) CreateOwnerProperties(ctx context.Context, arg CreateOwnerPropertiesParams) (OwnerProperty, error) {
	row := q.db.QueryRow(ctx, createOwnerProperties,
		arg.ListOfDate,
		arg.ListOfNotes,
		arg.ListOfAgent,
		arg.PropertyTitle,
		arg.PropertyTitleArabic,
		arg.Description,
		arg.DescriptionArabic,
		arg.IsVerified,
		arg.PropertyRank,
		arg.AddressesID,
		arg.LocationsID,
		arg.PropertyTypesID,
		arg.ProfilesID,
		arg.FacilitiesID,
		arg.AmenitiesID,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.IsShowOwnerInfo,
		arg.Property,
		arg.CountriesID,
		arg.RefNo,
		arg.Category,
		arg.Investment,
		arg.ContractStartDatetime,
		arg.ContractEndDatetime,
		arg.Amount,
		arg.UnitTypes,
		arg.UsersID,
		arg.PropertyName,
	)
	var i OwnerProperty
	err := row.Scan(
		&i.ID,
		&i.PropertyTitle,
		&i.PropertyTitleArabic,
		&i.Description,
		&i.DescriptionArabic,
		&i.IsVerified,
		&i.PropertyRank,
		&i.AddressesID,
		&i.LocationsID,
		&i.PropertyTypesID,
		&i.ProfilesID,
		&i.FacilitiesID,
		&i.AmenitiesID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsShowOwnerInfo,
		&i.Property,
		&i.CountriesID,
		&i.RefNo,
		&i.Category,
		&i.Investment,
		&i.ContractStartDatetime,
		&i.ContractEndDatetime,
		&i.Amount,
		&i.UnitTypes,
		&i.UsersID,
		&i.PropertyName,
		&i.ListOfDate,
		&i.ListOfNotes,
		&i.ListOfAgent,
	)
	return i, err
}

const deleteOwnerProperties = `-- name: DeleteOwnerProperties :exec
DELETE FROM owner_properties
Where id = $1
`

func (q *Queries) DeleteOwnerProperties(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteOwnerProperties, id)
	return err
}

const getAllOwnerProperties = `-- name: GetAllOwnerProperties :many
SELECT id, property_title, property_title_arabic, description, description_arabic, is_verified, property_rank, addresses_id, locations_id, property_types_id, profiles_id, facilities_id, amenities_id, status, created_at, updated_at, is_show_owner_info, property, countries_id, ref_no, category, investment, contract_start_datetime, contract_end_datetime, amount, unit_types, users_id, property_name, list_of_date, list_of_notes, list_of_agent FROM owner_properties
ORDER BY id
LIMIT $1
OFFSET $2
`

type GetAllOwnerPropertiesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetAllOwnerProperties(ctx context.Context, arg GetAllOwnerPropertiesParams) ([]OwnerProperty, error) {
	rows, err := q.db.Query(ctx, getAllOwnerProperties, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OwnerProperty
	for rows.Next() {
		var i OwnerProperty
		if err := rows.Scan(
			&i.ID,
			&i.PropertyTitle,
			&i.PropertyTitleArabic,
			&i.Description,
			&i.DescriptionArabic,
			&i.IsVerified,
			&i.PropertyRank,
			&i.AddressesID,
			&i.LocationsID,
			&i.PropertyTypesID,
			&i.ProfilesID,
			&i.FacilitiesID,
			&i.AmenitiesID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsShowOwnerInfo,
			&i.Property,
			&i.CountriesID,
			&i.RefNo,
			&i.Category,
			&i.Investment,
			&i.ContractStartDatetime,
			&i.ContractEndDatetime,
			&i.Amount,
			&i.UnitTypes,
			&i.UsersID,
			&i.PropertyName,
			&i.ListOfDate,
			&i.ListOfNotes,
			&i.ListOfAgent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOwnerProperties = `-- name: GetOwnerProperties :one
SELECT id, property_title, property_title_arabic, description, description_arabic, is_verified, property_rank, addresses_id, locations_id, property_types_id, profiles_id, facilities_id, amenities_id, status, created_at, updated_at, is_show_owner_info, property, countries_id, ref_no, category, investment, contract_start_datetime, contract_end_datetime, amount, unit_types, users_id, property_name, list_of_date, list_of_notes, list_of_agent FROM owner_properties 
WHERE id = $1 LIMIT $1
`

func (q *Queries) GetOwnerProperties(ctx context.Context, limit int32) (OwnerProperty, error) {
	row := q.db.QueryRow(ctx, getOwnerProperties, limit)
	var i OwnerProperty
	err := row.Scan(
		&i.ID,
		&i.PropertyTitle,
		&i.PropertyTitleArabic,
		&i.Description,
		&i.DescriptionArabic,
		&i.IsVerified,
		&i.PropertyRank,
		&i.AddressesID,
		&i.LocationsID,
		&i.PropertyTypesID,
		&i.ProfilesID,
		&i.FacilitiesID,
		&i.AmenitiesID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsShowOwnerInfo,
		&i.Property,
		&i.CountriesID,
		&i.RefNo,
		&i.Category,
		&i.Investment,
		&i.ContractStartDatetime,
		&i.ContractEndDatetime,
		&i.Amount,
		&i.UnitTypes,
		&i.UsersID,
		&i.PropertyName,
		&i.ListOfDate,
		&i.ListOfNotes,
		&i.ListOfAgent,
	)
	return i, err
}

const getOwnerPropertiesByName = `-- name: GetOwnerPropertiesByName :one
SELECT id, property_title, property_title_arabic, description, description_arabic, is_verified, property_rank, addresses_id, locations_id, property_types_id, profiles_id, facilities_id, amenities_id, status, created_at, updated_at, is_show_owner_info, property, countries_id, ref_no, category, investment, contract_start_datetime, contract_end_datetime, amount, unit_types, users_id, property_name, list_of_date, list_of_notes, list_of_agent FROM owner_properties 
WHERE property_title = $2 LIMIT $1
`

type GetOwnerPropertiesByNameParams struct {
	Limit         int32  `json:"limit"`
	PropertyTitle string `json:"property_title"`
}

func (q *Queries) GetOwnerPropertiesByName(ctx context.Context, arg GetOwnerPropertiesByNameParams) (OwnerProperty, error) {
	row := q.db.QueryRow(ctx, getOwnerPropertiesByName, arg.Limit, arg.PropertyTitle)
	var i OwnerProperty
	err := row.Scan(
		&i.ID,
		&i.PropertyTitle,
		&i.PropertyTitleArabic,
		&i.Description,
		&i.DescriptionArabic,
		&i.IsVerified,
		&i.PropertyRank,
		&i.AddressesID,
		&i.LocationsID,
		&i.PropertyTypesID,
		&i.ProfilesID,
		&i.FacilitiesID,
		&i.AmenitiesID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsShowOwnerInfo,
		&i.Property,
		&i.CountriesID,
		&i.RefNo,
		&i.Category,
		&i.Investment,
		&i.ContractStartDatetime,
		&i.ContractEndDatetime,
		&i.Amount,
		&i.UnitTypes,
		&i.UsersID,
		&i.PropertyName,
		&i.ListOfDate,
		&i.ListOfNotes,
		&i.ListOfAgent,
	)
	return i, err
}

const getOwnerPropertiesByRefrenceNumber = `-- name: GetOwnerPropertiesByRefrenceNumber :one
SELECT id, property_title, property_title_arabic, description, description_arabic, is_verified, property_rank, addresses_id, locations_id, property_types_id, profiles_id, facilities_id, amenities_id, status, created_at, updated_at, is_show_owner_info, property, countries_id, ref_no, category, investment, contract_start_datetime, contract_end_datetime, amount, unit_types, users_id, property_name, list_of_date, list_of_notes, list_of_agent FROM owner_properties WHERE ref_no = $1 LIMIT 1
`

func (q *Queries) GetOwnerPropertiesByRefrenceNumber(ctx context.Context, refNo string) (OwnerProperty, error) {
	row := q.db.QueryRow(ctx, getOwnerPropertiesByRefrenceNumber, refNo)
	var i OwnerProperty
	err := row.Scan(
		&i.ID,
		&i.PropertyTitle,
		&i.PropertyTitleArabic,
		&i.Description,
		&i.DescriptionArabic,
		&i.IsVerified,
		&i.PropertyRank,
		&i.AddressesID,
		&i.LocationsID,
		&i.PropertyTypesID,
		&i.ProfilesID,
		&i.FacilitiesID,
		&i.AmenitiesID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsShowOwnerInfo,
		&i.Property,
		&i.CountriesID,
		&i.RefNo,
		&i.Category,
		&i.Investment,
		&i.ContractStartDatetime,
		&i.ContractEndDatetime,
		&i.Amount,
		&i.UnitTypes,
		&i.UsersID,
		&i.PropertyName,
		&i.ListOfDate,
		&i.ListOfNotes,
		&i.ListOfAgent,
	)
	return i, err
}

const getOwnerPropertiesByUserId = `-- name: GetOwnerPropertiesByUserId :many
select id, property_title,  property from owner_properties op where op.users_id  = $1
`

type GetOwnerPropertiesByUserIdRow struct {
	ID            int64  `json:"id"`
	PropertyTitle string `json:"property_title"`
	Property      int64  `json:"property"`
}

func (q *Queries) GetOwnerPropertiesByUserId(ctx context.Context, usersID int64) ([]GetOwnerPropertiesByUserIdRow, error) {
	rows, err := q.db.Query(ctx, getOwnerPropertiesByUserId, usersID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOwnerPropertiesByUserIdRow
	for rows.Next() {
		var i GetOwnerPropertiesByUserIdRow
		if err := rows.Scan(&i.ID, &i.PropertyTitle, &i.Property); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOwnerPropertiesWithValidation = `-- name: GetOwnerPropertiesWithValidation :one
SELECT
    id,
    property_title,
    property_title_arabic,
    description,
    description_arabic,
    is_verified,
    property_rank,
    addresses_id,
    locations_id,
    property_types_id,
    profiles_id,
    facilities_id,
    amenities_id,
    status,
    created_at,
    updated_at,
    is_show_owner_info,
    property,
    countries_id,
    ref_no,
    category,
    investment,
    contract_start_datetime,
    contract_end_datetime,
    amount,
    unit_types,
    users_id,
    property_name,
    list_of_date,
    list_of_notes,
    list_of_agent
FROM
    owner_properties fp
WHERE
    CASE
        WHEN $1 :: bigint = 0 THEN true
        WHEN $1 :: bigint = 1 THEN fp.addresses_id IN (
            SELECT
                id
            FROM
                addresses
            WHERE
                addresses.cities_id = $2
        )
        WHEN $1 :: bigint = 2 THEN fp.addresses_id IN (
            SELECT
                id
            FROM
                addresses
            WHERE
                addresses.cities_id = $2
                AND communities_id = ANY($3 :: bigint [])
        )
        WHEN $1 :: bigint = 3 THEN fp.addresses_id IN (
            SELECT
                id
            FROM
                addresses
            WHERE
                addresses.cities_id = $2
                AND communities_id = ANY($3 :: bigint [])
                AND sub_communities_id = ANY($4 :: bigint [])
        )
        WHEN $1 :: bigint = 4 THEN fp.addresses_id IN (
            SELECT
                id
            FROM
                addresses
            WHERE
                addresses.cities_id = $2
                AND communities_id = ANY($3 :: bigint [])
                AND sub_communities_id = ANY($4 :: bigint [])
                AND addresses.locations_id = $5
        )
    END
    AND (
        status != 5
        AND status != 6
    )
    AND fp.id = $6
LIMIT
    1
`

type GetOwnerPropertiesWithValidationParams struct {
	Column1     int64       `json:"column_1"`
	CitiesID    pgtype.Int8 `json:"cities_id"`
	Column3     []int64     `json:"column_3"`
	Column4     []int64     `json:"column_4"`
	LocationsID pgtype.Int8 `json:"locations_id"`
	ID          int64       `json:"id"`
}

func (q *Queries) GetOwnerPropertiesWithValidation(ctx context.Context, arg GetOwnerPropertiesWithValidationParams) (OwnerProperty, error) {
	row := q.db.QueryRow(ctx, getOwnerPropertiesWithValidation,
		arg.Column1,
		arg.CitiesID,
		arg.Column3,
		arg.Column4,
		arg.LocationsID,
		arg.ID,
	)
	var i OwnerProperty
	err := row.Scan(
		&i.ID,
		&i.PropertyTitle,
		&i.PropertyTitleArabic,
		&i.Description,
		&i.DescriptionArabic,
		&i.IsVerified,
		&i.PropertyRank,
		&i.AddressesID,
		&i.LocationsID,
		&i.PropertyTypesID,
		&i.ProfilesID,
		&i.FacilitiesID,
		&i.AmenitiesID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsShowOwnerInfo,
		&i.Property,
		&i.CountriesID,
		&i.RefNo,
		&i.Category,
		&i.Investment,
		&i.ContractStartDatetime,
		&i.ContractEndDatetime,
		&i.Amount,
		&i.UnitTypes,
		&i.UsersID,
		&i.PropertyName,
		&i.ListOfDate,
		&i.ListOfNotes,
		&i.ListOfAgent,
	)
	return i, err
}

const updateOwnerProperties = `-- name: UpdateOwnerProperties :one
UPDATE owner_properties
SET   property_title = $2,
  property_title_arabic = $3,
  description = $4,
  description_arabic = $5,
  is_verified = $6,
  property_rank = $7,
  addresses_id = $8,
  locations_id = $9,
  property_types_id = $10,
  profiles_id = $11,
  facilities_id = $12,
  amenities_id = $13,
  status = $14,
  created_at = $15,
  updated_at = $16,
  is_show_owner_info = $17,
  property = $18,
  -- facts_values = $19,
  countries_id = $19,
  ref_no = $20,
  category = $21,
  investment = $22,
  contract_start_datetime = $23,
  contract_end_datetime = $24,
  amount = $25,
  -- ask_price = $26,
  unit_types = $26,
    users_id = $27,
    property_name = $28,
      list_of_date = $29,
  list_of_notes =  $30,
  list_of_agent = $31  
Where id = $1
RETURNING id, property_title, property_title_arabic, description, description_arabic, is_verified, property_rank, addresses_id, locations_id, property_types_id, profiles_id, facilities_id, amenities_id, status, created_at, updated_at, is_show_owner_info, property, countries_id, ref_no, category, investment, contract_start_datetime, contract_end_datetime, amount, unit_types, users_id, property_name, list_of_date, list_of_notes, list_of_agent
`

type UpdateOwnerPropertiesParams struct {
	ID                    int64              `json:"id"`
	PropertyTitle         string             `json:"property_title"`
	PropertyTitleArabic   string             `json:"property_title_arabic"`
	Description           string             `json:"description"`
	DescriptionArabic     string             `json:"description_arabic"`
	IsVerified            pgtype.Bool        `json:"is_verified"`
	PropertyRank          int64              `json:"property_rank"`
	AddressesID           int64              `json:"addresses_id"`
	LocationsID           int64              `json:"locations_id"`
	PropertyTypesID       int64              `json:"property_types_id"`
	ProfilesID            int64              `json:"profiles_id"`
	FacilitiesID          []int64            `json:"facilities_id"`
	AmenitiesID           []int64            `json:"amenities_id"`
	Status                int64              `json:"status"`
	CreatedAt             time.Time          `json:"created_at"`
	UpdatedAt             time.Time          `json:"updated_at"`
	IsShowOwnerInfo       pgtype.Bool        `json:"is_show_owner_info"`
	Property              int64              `json:"property"`
	CountriesID           int64              `json:"countries_id"`
	RefNo                 string             `json:"ref_no"`
	Category              string             `json:"category"`
	Investment            pgtype.Bool        `json:"investment"`
	ContractStartDatetime pgtype.Timestamptz `json:"contract_start_datetime"`
	ContractEndDatetime   pgtype.Timestamptz `json:"contract_end_datetime"`
	Amount                float64            `json:"amount"`
	UnitTypes             []int64            `json:"unit_types"`
	UsersID               int64              `json:"users_id"`
	PropertyName          string             `json:"property_name"`
	ListOfDate            []time.Time        `json:"list_of_date"`
	ListOfNotes           []string           `json:"list_of_notes"`
	ListOfAgent           []int64            `json:"list_of_agent"`
}

func (q *Queries) UpdateOwnerProperties(ctx context.Context, arg UpdateOwnerPropertiesParams) (OwnerProperty, error) {
	row := q.db.QueryRow(ctx, updateOwnerProperties,
		arg.ID,
		arg.PropertyTitle,
		arg.PropertyTitleArabic,
		arg.Description,
		arg.DescriptionArabic,
		arg.IsVerified,
		arg.PropertyRank,
		arg.AddressesID,
		arg.LocationsID,
		arg.PropertyTypesID,
		arg.ProfilesID,
		arg.FacilitiesID,
		arg.AmenitiesID,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.IsShowOwnerInfo,
		arg.Property,
		arg.CountriesID,
		arg.RefNo,
		arg.Category,
		arg.Investment,
		arg.ContractStartDatetime,
		arg.ContractEndDatetime,
		arg.Amount,
		arg.UnitTypes,
		arg.UsersID,
		arg.PropertyName,
		arg.ListOfDate,
		arg.ListOfNotes,
		arg.ListOfAgent,
	)
	var i OwnerProperty
	err := row.Scan(
		&i.ID,
		&i.PropertyTitle,
		&i.PropertyTitleArabic,
		&i.Description,
		&i.DescriptionArabic,
		&i.IsVerified,
		&i.PropertyRank,
		&i.AddressesID,
		&i.LocationsID,
		&i.PropertyTypesID,
		&i.ProfilesID,
		&i.FacilitiesID,
		&i.AmenitiesID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsShowOwnerInfo,
		&i.Property,
		&i.CountriesID,
		&i.RefNo,
		&i.Category,
		&i.Investment,
		&i.ContractStartDatetime,
		&i.ContractEndDatetime,
		&i.Amount,
		&i.UnitTypes,
		&i.UsersID,
		&i.PropertyName,
		&i.ListOfDate,
		&i.ListOfNotes,
		&i.ListOfAgent,
	)
	return i, err
}

const updateOwnerPropertyRankById = `-- name: UpdateOwnerPropertyRankById :one
UPDATE owner_properties
SET property_rank = $2
WHERE id=$1
RETURNING id, property_title, property_title_arabic, description, description_arabic, is_verified, property_rank, addresses_id, locations_id, property_types_id, profiles_id, facilities_id, amenities_id, status, created_at, updated_at, is_show_owner_info, property, countries_id, ref_no, category, investment, contract_start_datetime, contract_end_datetime, amount, unit_types, users_id, property_name, list_of_date, list_of_notes, list_of_agent
`

type UpdateOwnerPropertyRankByIdParams struct {
	ID           int64 `json:"id"`
	PropertyRank int64 `json:"property_rank"`
}

func (q *Queries) UpdateOwnerPropertyRankById(ctx context.Context, arg UpdateOwnerPropertyRankByIdParams) (OwnerProperty, error) {
	row := q.db.QueryRow(ctx, updateOwnerPropertyRankById, arg.ID, arg.PropertyRank)
	var i OwnerProperty
	err := row.Scan(
		&i.ID,
		&i.PropertyTitle,
		&i.PropertyTitleArabic,
		&i.Description,
		&i.DescriptionArabic,
		&i.IsVerified,
		&i.PropertyRank,
		&i.AddressesID,
		&i.LocationsID,
		&i.PropertyTypesID,
		&i.ProfilesID,
		&i.FacilitiesID,
		&i.AmenitiesID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsShowOwnerInfo,
		&i.Property,
		&i.CountriesID,
		&i.RefNo,
		&i.Category,
		&i.Investment,
		&i.ContractStartDatetime,
		&i.ContractEndDatetime,
		&i.Amount,
		&i.UnitTypes,
		&i.UsersID,
		&i.PropertyName,
		&i.ListOfDate,
		&i.ListOfNotes,
		&i.ListOfAgent,
	)
	return i, err
}

const updateOwnerPropertyStatusById = `-- name: UpdateOwnerPropertyStatusById :one
UPDATE owner_properties
SET status = $2
WHERE id=$1
RETURNING id, property_title, property_title_arabic, description, description_arabic, is_verified, property_rank, addresses_id, locations_id, property_types_id, profiles_id, facilities_id, amenities_id, status, created_at, updated_at, is_show_owner_info, property, countries_id, ref_no, category, investment, contract_start_datetime, contract_end_datetime, amount, unit_types, users_id, property_name, list_of_date, list_of_notes, list_of_agent
`

type UpdateOwnerPropertyStatusByIdParams struct {
	ID     int64 `json:"id"`
	Status int64 `json:"status"`
}

func (q *Queries) UpdateOwnerPropertyStatusById(ctx context.Context, arg UpdateOwnerPropertyStatusByIdParams) (OwnerProperty, error) {
	row := q.db.QueryRow(ctx, updateOwnerPropertyStatusById, arg.ID, arg.Status)
	var i OwnerProperty
	err := row.Scan(
		&i.ID,
		&i.PropertyTitle,
		&i.PropertyTitleArabic,
		&i.Description,
		&i.DescriptionArabic,
		&i.IsVerified,
		&i.PropertyRank,
		&i.AddressesID,
		&i.LocationsID,
		&i.PropertyTypesID,
		&i.ProfilesID,
		&i.FacilitiesID,
		&i.AmenitiesID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsShowOwnerInfo,
		&i.Property,
		&i.CountriesID,
		&i.RefNo,
		&i.Category,
		&i.Investment,
		&i.ContractStartDatetime,
		&i.ContractEndDatetime,
		&i.Amount,
		&i.UnitTypes,
		&i.UsersID,
		&i.PropertyName,
		&i.ListOfDate,
		&i.ListOfNotes,
		&i.ListOfAgent,
	)
	return i, err
}

const updateOwnerPropertyVerificationById = `-- name: UpdateOwnerPropertyVerificationById :one
UPDATE owner_properties
SET is_verified = $2
WHERE id=$1
RETURNING id, property_title, property_title_arabic, description, description_arabic, is_verified, property_rank, addresses_id, locations_id, property_types_id, profiles_id, facilities_id, amenities_id, status, created_at, updated_at, is_show_owner_info, property, countries_id, ref_no, category, investment, contract_start_datetime, contract_end_datetime, amount, unit_types, users_id, property_name, list_of_date, list_of_notes, list_of_agent
`

type UpdateOwnerPropertyVerificationByIdParams struct {
	ID         int64       `json:"id"`
	IsVerified pgtype.Bool `json:"is_verified"`
}

func (q *Queries) UpdateOwnerPropertyVerificationById(ctx context.Context, arg UpdateOwnerPropertyVerificationByIdParams) (OwnerProperty, error) {
	row := q.db.QueryRow(ctx, updateOwnerPropertyVerificationById, arg.ID, arg.IsVerified)
	var i OwnerProperty
	err := row.Scan(
		&i.ID,
		&i.PropertyTitle,
		&i.PropertyTitleArabic,
		&i.Description,
		&i.DescriptionArabic,
		&i.IsVerified,
		&i.PropertyRank,
		&i.AddressesID,
		&i.LocationsID,
		&i.PropertyTypesID,
		&i.ProfilesID,
		&i.FacilitiesID,
		&i.AmenitiesID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsShowOwnerInfo,
		&i.Property,
		&i.CountriesID,
		&i.RefNo,
		&i.Category,
		&i.Investment,
		&i.ContractStartDatetime,
		&i.ContractEndDatetime,
		&i.Amount,
		&i.UnitTypes,
		&i.UsersID,
		&i.PropertyName,
		&i.ListOfDate,
		&i.ListOfNotes,
		&i.ListOfAgent,
	)
	return i, err
}
